model:
  base: "/home/yzj/anima/AnimateDiff/models/StableDiffusion"
motion_module:
  path: "/home/yzj/anima/AnimateDiff/models/Motion_Module/mm_sd_v15_v2.ckpt"
prompt: "a cat walking in the park"
n_prompt: "bad quality, worst quality"
sample_size: [256, 256]
L: 8
